### ISSUE TITLE
CollisionInitializer

### ISSUE THREAD

**Issue by PhanaticD** [plushmonkey/JedCore#43]
currently it looks like collisions are defined per move with another move, I feel like

ProjectKorra.getCollisionInitializer().addSmall/LargeAbility(ability)
 
should be used instead, this will make it work with more moves, as well as addons, at least in the case of general "small" or "big" moves that dont need to do anything special with collisions

**Comment by plushmonkey** [comment]
I'm not sure what you mean.

Collisions are defined in the config and they aren't limited to just the ones in there by default. The default ones are just there as an example for adding more.  It already works with addon abilities.

I don't want to use the small/large system because it doesn't have the granular control that the current system has.

**Comment by PhanaticD** [comment]
there should be the option to use it then though, so i dont have to go through and manually type out for 50 moves

**Comment by plushmonkey** [comment]
Yeah, I can add the option. I was never a fan of having everything collidable, so I never had the need to implement it.
